### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by simonecrevatin** [justinwilkin/atem-timecode-overlay#1]
does not work , the browser responds : The site can not provide a secure connection

**Comment by justinwilkin** [comment]
> does not work , the browser responds : The site can not provide a secure connection

Could you try using http://localhost:3000 or just localhost:3000 in your browser. That error typically means you are trying to access the resource through SSL which is not supported by localhost. 

i.e. instead of using https://localhost:3000 use http://localhost:3000 and it will work.
